repos:
  - repo: https://github.com/psf/black
    rev: c6755bb741b6481d6b3d3bb563c83fa060db96c9  # frozen: 26.3.1
    hooks:
      - id: black

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: e05c5c0818279e5ac248ac9e954431ba58865e61  # frozen: v0.15.7
    hooks:
      - id: ruff

  - repo: https://github.com/pycqa/isort
    rev: a333737ed43df02b18e6c95477ea1b285b3de15a  # frozen: 8.0.1
    hooks:
      - id: isort

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: 81b795a41ddcc3c77218d8c8e406983e39852285  # frozen: v1.1.408
    hooks:
      - id: pyright
        args: ["--project", "pyproject.toml"]
